name: auto_release

on:
  workflow_dispatch:
    inputs:
      device:
        required: true
      prefix:
        required: false
        default: ""
      ksu:
        required: true
      chat_id:
        required: false

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      device: ${{ inputs.device }}
      prefix: ${{ inputs.prefix }}
      ksu: ${{ inputs.ksu }}
    secrets:
      repo: ${{ secrets.REPO }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      chat_id: ${{ inputs.chat_id }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_SAVE_FILE: ${{ secrets.TELEGRAM_SAVE_FILE }}
